### ISSUE TITLE
Any plans for macOS?

### ISSUE THREAD

**Issue by Rychillie** [adithyasource/moment#1]
Any plans for macOS?

**Comment by adithyasource** [comment]
number 1 priority at the moment! should be out in a few days ^-^

**Comment by adithyasource** [comment]
so looks like there's a whole bunch of problems with the underlying libraries regarding their macos implementation which basically means i'll have to rebuild the entire app from scratch for macos. this issue came up unexpectedly and basically blocks my plans for a macos release until that is fixed. really sorry about that, but i'm not able to warrant a rebuild of the entire application at the moment, but it definitely is going to be on my radar after my next project.
